run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - gosec         # Security checks
    - bodyclose     # HTTP body close check
    - nilerr        # nil error check
    - copyloopvar   # Loop variable capture (replaces deprecated exportloopref)

linters-settings:
  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G204  # Subprocess launched with variable - intentional for container runtime
      - G304  # File path provided by user - intentional for validate command
  misspell:
    locale: US
  goimports:
    local-prefixes: github.com/3rg0n/bjarne

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
