# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: bjarne

before:
  hooks:
    - go mod tidy

builds:
  - id: bjarne
    main: .
    binary: bjarne
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Commit={{.ShortCommit}}
      - -X main.Date={{.Date}}
    # Windows-specific naming
    hooks:
      post:
        - cmd: '{{ if eq .Os "windows" }}echo "Built Windows binary"{{ end }}'

archives:
  - id: default
    formats:
      - tar.gz
    # Windows gets zip
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: 3rg0n
    name: bjarne
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
  header: |
    ## bjarne {{ .Version }}

    AI-assisted C/C++ code generation with mandatory validation using Clang sanitizers.

    ### Installation

    **macOS/Linux (Homebrew):**
    ```bash
    brew install 3rg0n/tap/bjarne
    ```

    **Windows (Scoop):**
    ```powershell
    scoop bucket add bjarne https://github.com/3rg0n/scoop-bucket
    scoop install bjarne
    ```

    **Windows (PowerShell one-liner):**
    ```powershell
    irm https://raw.githubusercontent.com/3rg0n/bjarne/master/install.ps1 | iex
    ```

    **Or download a binary below** and add to your PATH.

    ### Requirements
    - **Podman** or **Docker** (for validation container)
    - **LLM Provider** (one of):
      - AWS Bedrock (default) - requires AWS credentials
      - Anthropic API - set `BJARNE_PROVIDER=anthropic` and `BJARNE_API_KEY`
      - OpenAI API - set `BJARNE_PROVIDER=openai` and `BJARNE_API_KEY`
      - Google Gemini - set `BJARNE_PROVIDER=gemini` and `BJARNE_API_KEY`

    ### Quick Start
    ```bash
    bjarne
    > write a thread-safe counter in C++
    ```
    On first run, bjarne will prompt to download the validation container (~500MB).
  footer: |

    ---
    **Full documentation:** https://github.com/3rg0n/bjarne

# Homebrew tap - requires HOMEBREW_TAP_TOKEN secret and 3rg0n/homebrew-tap repo
brews:
  - repository:
      owner: 3rg0n
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/3rg0n/bjarne"
    description: "AI-assisted C/C++ code generation with rigorous validation"
    license: "MIT"
    install: |
      bin.install "bjarne"
    test: |
      system "#{bin}/bjarne", "--version"
    dependencies:
      - name: podman
        type: optional
    caveats: |
      bjarne requires podman or docker for code validation.
      Install with: brew install podman
    # Skip if token not configured
    skip_upload: auto

# Scoop bucket for Windows - requires SCOOP_BUCKET_TOKEN secret and 3rg0n/scoop-bucket repo
scoops:
  - repository:
      owner: 3rg0n
      name: scoop-bucket
      token: "{{ .Env.SCOOP_BUCKET_TOKEN }}"
    homepage: "https://github.com/3rg0n/bjarne"
    description: "AI-assisted C/C++ code generation with rigorous validation"
    license: "MIT"
    # Skip if token not configured
    skip_upload: auto

# Announce releases
announce:
  skip: true
